#!/bin/bash -eux
# Install:
#  - eclipse
#  - IntelliJ IDEA
#  - groovy
#  - gradle
#  - scala
# A JDK have to be already installed on the system

# Configuration for eclipse
ECLIPSE_VERSION_NAME=mars
ECLIPSE_VERSION_RELEASE=R
ECLIPSE_DEST_PATH=/opt
ECLIPSE_DEST_NAME="eclipse-java-${ECLIPSE_VERSION_NAME}"
ECLIPSE_MENU_NAME="Eclipse ${ECLIPSE_VERSION_NAME} (Java)"

# Configuration for IntelliJ IDEA
IDEA_ARCHIVE=ideaIC-14.1.4.tar.gz
IDEA_URL="http://download.jetbrains.com/idea/${IDEA_ARCHIVE}"
IDEA_DEST_PATH=/opt

# Configuration for groovy
GROOVY_ARCHIVE=apache-groovy-sdk-2.4.4.zip
GROOVY_URL=http://dl.bintray.com/groovy/maven/${GROOVY_ARCHIVE}
GROOVY_DESTPATH=/opt

# Configuration for gradle
GRADLE_ARCHIVE=gradle-2.6-all.zip
GRADLE_URL=https://services.gradle.org/distributions/${GRADLE_ARCHIVE}
GRADLE_DESTPATH=/opt

# Configuration for scala
SCALA_VERSION=2.11.7
SCALA_ARCHIVE=scala-${SCALA_VERSION}.tgz
SCALA_URL=http://downloads.typesafe.com/scala/${SCALA_VERSION}/${SCALA_ARCHIVE}
SCALA_DESTPATH=/opt

# Install the eclipse Java IDE

# Build archive name and URL
ECLIPSE_ARCHITECTURE=""
if [ $(uname -m) = 'x86_64' ]; then
    ECLIPSE_ARCHITECTURE="-x86_64"
fi

ECLIPSE_ARCHIVE="eclipse-java-${ECLIPSE_VERSION_NAME}-${ECLIPSE_VERSION_RELEASE}-linux-gtk${ECLIPSE_ARCHITECTURE}.tar.gz"
ECLIPSE_URL="https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/${ECLIPSE_VERSION_NAME}/${ECLIPSE_VERSION_RELEASE}/${ECLIPSE_ARCHIVE}&r=1"

# Downloading eclipse
wget -O $ECLIPSE_ARCHIVE $ECLIPSE_URL

# installing
tar -C $ECLIPSE_DEST_PATH -xaf $ECLIPSE_ARCHIVE
mv $ECLIPSE_DEST_PATH/eclipse $ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME
chown -R root:root $ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME

# Remove archive
rm -f $ECLIPSE_ARCHIVE

# installing plugins
$ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/eclipse \
-clean -purgeHistory \
-application org.eclipse.equinox.p2.director \
-noSplash \
-repository \
http://download.eclipse.org/releases/${ECLIPSE_VERSION_NAME},\
http://eclipse-cs.sf.net/update,\
http://findbugs.cs.umd.edu/eclipse,\
http://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/,\
http://eclipse-color-theme.github.com/update \
-installIUs \
net.sf.eclipsecs.feature.group,\
com.github.sevntu.checkstyle.checks.feature.feature.group,\
edu.umd.cs.findbugs.plugin.eclipse.feature.group,\
net.sourceforge.pmd.eclipse.feature.group,\
org.eclipse.team.svn.feature.group,\
org.eclipse.team.svn.resource.ignore.rules.jdt.feature.group,\
org.eclipse.team.svn.revision.graph.feature.group,\
org.eclipse.team.svn.nl1.feature.group,\
com.github.eclipsecolortheme.feature.feature.group \
-vmargs -Declipse.p2.mirrors=true

# Generate an eclipse launcher
(
cat <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=$ECLIPSE_MENU_NAME
Comment=Eclipse IDE
Exec=$ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/eclipse
Icon=$ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/icon.xpm
Terminal=false
Type=Application
Categories=GNOME;Application;Development;
StartupNotify=true
EOF
) > /usr/share/applications/$ECLIPSE_DEST_NAME.desktop

# Define the path of the workspace
sed -i -e "s/^--launcher.defaultAction$/-data\n@user.home\/$ECLIPSE_DEST_NAME-workspace\n--launcher.defaultAction/" \
    $ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/eclipse.ini

# Install the Intellij IDEA IDE

# Downloading
wget -O $IDEA_ARCHIVE $IDEA_URL

# installing
tar -C $IDEA_DEST_PATH -xaf $IDEA_ARCHIVE

# Remove archive
rm -f $IDEA_ARCHIVE

# Create a symlink to IDEA path
IDEA_PATH=$(ls $IDEA_DEST_PATH | grep idea)
ln -s $IDEA_DEST_PATH/$IDEA_PATH $IDEA_DEST_PATH/idea

# Generate a launcher
(
cat <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=IntelliJ IDEA
Comment=IntelliJ IDEA IDE
Exec=$IDEA_DEST_PATH/idea/bin/idea.sh
Icon=$IDEA_DEST_PATH/idea/bin/idea.png
Terminal=false
Type=Application
Categories=GNOME;Application;Development;
StartupNotify=true"
EOF
) > /usr/share/applications/idea.desktop

# Install the GROOVY SDK
# Downloading
wget -O $GROOVY_ARCHIVE $GROOVY_URL

# installing
unzip -d $GROOVY_DESTPATH $GROOVY_ARCHIVE

# Remove archive
rm -f $GROOVY_ARCHIVE

# Create a symlink to GROOVY path
GROOVY_PATH=$(ls $GROOVY_DESTPATH | grep groovy)
ln -s $GROOVY_DESTPATH/$GROOVY_PATH $GROOVY_DESTPATH/groovy

# Set environment variables
GROOVY_HOME=/opt/groovy
sed -i '/^PATH/ s/$/:\/opt\/groovy\/bin/' /etc/environment
echo "GROOVY_HOME=$GROOVY_HOME" >> /etc/environment

# Install Gradle
# Downloading
wget -O $GRADLE_ARCHIVE $GRADLE_URL

# installing
unzip -d $GRADLE_DESTPATH $GRADLE_ARCHIVE

# Remove archive
rm -f $GRADLE_ARCHIVE

# Create a symlink to GRADLE path
GRADLE_PATH=$(ls $GRADLE_DESTPATH | grep gradle)
ln -s $GRADLE_DESTPATH/$GRADLE_PATH $GRADLE_DESTPATH/gradle

# Set environment variables
GRADLE_HOME=/opt/gradle
sed -i '/^PATH/ s/$/:\/opt\/gradle\/bin/' /etc/environment
echo "GRADLE_HOME=$GRADLE_HOME" >> /etc/environment

# Install Scala
# Downloading
wget -O $SCALA_ARCHIVE $SCALA_URL

# installing
tar -C $SCALA_DESTPATH -xaf $SCALA_ARCHIVE

# Remove archive
rm -f $SCALA_ARCHIVE

# Create a symlink to SCALA path
SCALA_PATH=$(ls $SCALA_DESTPATH | grep scala)
ln -s $SCALA_DESTPATH/$SCALA_PATH $SCALA_DESTPATH/scala

# Set environment variables
SCALA_HOME=/opt/scala
sed -i '/^PATH/ s/$/:\/opt\/scala\/bin/' /etc/environment
echo "SCALA_HOME=$SCALA_HOME" >> /etc/environment

