#!/bin/bash -e

# Configuration for sage-math
SAGE_VERSION=6.8
SAGE_ARCHIVE=sage-${SAGE_VERSION}-x86_64-Linux-Ubuntu_14.04_64_bit.tar.lrz
SAGE_URL=http://www.mirrorservice.org/sites/www.sagemath.org/linux/64bit/${SAGE_ARCHIVE}
SAGE_DESTPATH=/opt

# Application conf.
APP_CFG_DIR=/home/user/.local/share/applications/
APP_CFG_FILE=defaults.list

DEV_EDITOR='geany.desktop'

# Associate mime-type ($1) with an application ($2)
function associate {
  if grep $1 ${APP_CFG_DIR}${APP_CFG_FILE}; then # found
    MIME_TYPE=${1/\//\\\/}
    sed -i "s/${MIME_TYPE}=.*/${MIME_TYPE}=$2/" ${APP_CFG_DIR}${APP_CFG_FILE}
  else # not found
    echo "$1=$2" >> ${APP_CFG_DIR}${APP_CFG_FILE}
  fi
}

if [ ! -d ${APP_CFG_DIR} ]; then
  mkdir -p ${APP_CFG_DIR}
  chown user:users ${APP_CFG_DIR}
fi

if [ ! -f ${APP_CFG_DIR}${APP_CFG_FILE} ]; then
  echo "[Default Applications]" > ${APP_CFG_DIR}${APP_CFG_FILE}
  chown user:users ${APP_CFG_DIR}${APP_CFG_FILE}
fi

# File association
associate 'text/x-tex' ${DEV_EDITOR}

# Tous les fichiers copiés doivent appartenir à user
chown -R user:users ~user/.config

# Install sage
# Downloading
wget -O $SAGE_ARCHIVE $SAGE_URL

# installing
lrzuntar -O $SAGE_DESTPATH $SAGE_ARCHIVE

# Remove archive
rm -f $SAGE_ARCHIVE

# Create a symlink to SAGE path
SAGE_PATH=$(ls $SAGE_DESTPATH | grep sage)
ln -s $SAGE_DESTPATH/$SAGE_PATH $SAGE_DESTPATH/sage

# Set environment variables
SAGE_HOME=/opt/sage
sed -i '/^PATH/ s/$/:\/opt\/sage/' /etc/environment
echo "SAGE_HOME=$SAGE_HOME" >> /etc/environment

