#!/bin/bash -e

# Declarations
OPENOCD_NAME=openocd
OPENOCD_VERSION=0.8.0
OPENOCD_FULLNAME="${OPENOCD_NAME}-${OPENOCD_VERSION}"

ECLIPSE_VERSION_NAME=kepler
ECLIPSE_VERSION_RELEASE=SR2
ECLIPSE_DEST_PATH=/opt
ECLIPSE_DEST_NAME="eclipse-cpp-${ECLIPSE_VERSION_NAME}"
ECLIPSE_MENU_NAME="Eclipse ${ECLIPSE_VERSION_NAME} (C++)"

# OpenOCD
wget -O "/tmp/${OPENOCD_FULLNAME}.tar.gz" "http://sourceforge.net/projects/openocd/files/openocd/${OPENOCD_VERSION}/${OPENOCD_FULLNAME}.tar.gz/download"
tar xf /tmp/${OPENOCD_FULLNAME}.tar.gz -C /usr/local/src/
# Compile in a subshell to keep base directory unchanged
(
cd /usr/local/src/${OPENOCD_FULLNAME}/
./configure --enable-stlink
make
make install
)

# Permissions
gpasswd -a user dialout
gpasswd -a user users
(
cat <<EOF
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="3748", MODE="0666"
EOF
) > /etc/udev/rules.d/99-stlinkv2.rules
udevadm control --reload-rules

# Eclipse

# Build archive name and URL
ECLIPSE_ARCHITECTURE=""
if [ $(uname -m) = 'x86_64' ]; then
    ECLIPSE_ARCHITECTURE="-x86_64"
fi

ECLIPSE_ARCHIVE="eclipse-cpp-${ECLIPSE_VERSION_NAME}-${ECLIPSE_VERSION_RELEASE}-linux-gtk${ECLIPSE_ARCHITECTURE}.tar.gz"
ECLIPSE_URL="https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/${ECLIPSE_VERSION_NAME}/${ECLIPSE_VERSION_RELEASE}/${ECLIPSE_ARCHIVE}&r=1"

# Downloading eclipse
wget -O $ECLIPSE_ARCHIVE $ECLIPSE_URL

# installing
tar -C $ECLIPSE_DEST_PATH -xaf $ECLIPSE_ARCHIVE
mv $ECLIPSE_DEST_PATH/eclipse $ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME
chown -R root:root $ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME

# Remove archive
rm -f $ECLIPSE_ARCHIVE

# installing plugins
$ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/eclipse \
-clean -purgeHistory \
-application org.eclipse.equinox.p2.director \
-noSplash \
-repository \
http://gnuarmeclipse.sourceforge.net/updates,\
http://download.eclipse.org/tools/cdt/releases/kepler/ \
-installIUs \
org.eclipse.cdt.debug.gdbjtag.ui,\
ilg.gnuarmeclipse.managedbuild.cross.feature.group,\
ilg.gnuarmeclipse.doc.user.feature.group,\
ilg.gnuarmeclipse.templates.freescale.feature.group,\
ilg.gnuarmeclipse.templates.cortexm.feature.group,\
ilg.gnuarmeclipse.debug.gdbjtag.jlink.feature.group,\
ilg.gnuarmeclipse.debug.gdbjtag.openocd.feature.group,\
ilg.gnuarmeclipse.packs.feature.group,\
ilg.gnuarmeclipse.templates.stm.feature.group \
-vmargs -Declipse.p2.mirrors=true

# Define the path of the workspace
sed -i -e "s/^--launcher.defaultAction$/-data\n@user.home\/$ECLIPSE_DEST_NAME-workspace\n--launcher.defaultAction/" \
    $ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/eclipse.ini

# Generate an eclipse launcher
(
cat <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=$ECLIPSE_MENU_NAME
Comment=Eclipse IDE
Exec=$ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/eclipse
Icon=$ECLIPSE_DEST_PATH/$ECLIPSE_DEST_NAME/icon.xpm
Terminal=false
Type=Application
Categories=GNOME;Application;Development;
StartupNotify=true
EOF
) > /usr/share/applications/$ECLIPSE_DEST_NAME.desktop

